{% set python_min = '3.9.0' %}
{% set name = "unicall" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unicall-{{ version }}.tar.gz
  sha256: c14816c7d8f898f766931e4fa1483178d9dca54f2d6ae7c453bacc88baa1fc18

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - uniserde >=0.3.6,<0.4.0

test:
  imports:
    - unicall
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/mad-moo/unicall
  summary: Easy to use RPC library based on uniserde
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
